version: '3.8'

services:
  app:
    build:
      context: ./app
    container_name: python-app
    depends_on:
      - db
    networks:
      - red-biblioteca

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - red-biblioteca

networks:
  red-biblioteca:
