version: '3.8'

networks:
  pipeline_net:
    name: pipeline_net        # nombre real en Docker
    driver: bridge
    # Fuerza el mismo set de flags siempre:
    ipam:
      driver: default
    enable_ipv6: false        # o true, pero SIEMPRE igual

services:
  web:
    build: ./app
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - pipeline_net          # ← usar la red fija

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - pipeline_net

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - pipeline_net

volumes:
  jenkins_home:
