services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: biblioteca
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    networks:
      - pipeline_net 

  web:
    build:
      context: .              
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - pipeline_net 

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - pipeline_net  

volumes:
  jenkins_home:
  mysql-data:

networks:
  pipeline_net:
    driver: bridge
