version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_biblioteca
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d  # 👈 aquí se monta el init.sql

  web:
    build: ./app
    container_name: flask_biblioteca
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development

volumes:
  db_data:
